# syntax=docker/dockerfile:1
FROM debian:12-slim

ARG NDK_VERSION=r26c

# 1. 필수 도구 설치
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    unzip \
    make \
    build-essential \
    git \
    perl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# 2. Android NDK 설치
RUN curl -SLO https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip \
    && unzip android-ndk-${NDK_VERSION}-linux.zip \
    && mv android-ndk-${NDK_VERSION} /opt/ndk \
    && rm android-ndk-${NDK_VERSION}-linux.zip

ENV ANDROID_NDK_ROOT=/opt/ndk

# 3. OpenSSL 소스 다운로드
WORKDIR /src
RUN git clone --depth=1 --branch openssl-3.4.1 https://github.com/openssl/openssl.git

# 4. OpenSSL 빌드 (arm64-v8a, armeabi-v7a 전용)
RUN for ABI in \
    "arm64-v8a android-arm64 aarch64-linux-android" \
    "armeabi-v7a android-arm armv7a-linux-androideabi"; do \
    set -- $ABI; \
    ABI_NAME=$1; CONFIGURE_NAME=$2; HOST=$3; \
    echo "====> Building OpenSSL for $ABI_NAME"; \
    export PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH; \
    PATH=$PATH which $HOST21-clang || (echo "❌ $HOST21-clang not found!" && exit 1); \
    PATH=$PATH which $HOST-ar || (echo "❌ $HOST-ar not found!" && exit 1); \
    cd /src/openssl && make clean || true; \
    PATH=$PATH ./Configure $CONFIGURE_NAME no-shared no-tests --prefix=/src/openssl/build/$ABI_NAME && \
    make CC=$HOST21-clang AR=$HOST-ar -j$(nproc) && \
    make install_sw; \
  done
