# syntax=docker/dockerfile:1
FROM debian:12-slim

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  git \
  wget \
  curl \
  unzip \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*
